/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetTimeInMicroSec */

#ifndef _Included_GetTimeInMicroSec
#define _Included_GetTimeInMicroSec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetTimeInMicroSec
 * Method:    get_time_in_microsec
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_GetTimeInMicroSec_get_1time_1in_1microsec
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
