/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StackTrace */

#ifndef _Included_StackTrace
#define _Included_StackTrace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StackTrace
 * Method:    do_print_stack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StackTrace_do_1print_1stack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
